version: "3.8"

services:
  react-app:
    container_name: blinklist-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - 3000:3000
    command: npm start

  mock-server:
    container_name: mock-server
    build: .
    volumes:
      - ./database:/app/database
    ports:
      - 4001:4001
    command: npx json-server --watch database/db.json --port 4001