version: "3.8"

services:
  react-app:
    container_name: blinklist-app

    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    command: npm start